### ISSUE TITLE
tron wallet

### ISSUE THREAD

**Issue by mnz12138** [yuzhiyou1990/TronWebSwift#1]
There is no example of tron creating a wallet

**Comment by yuzhiyou1990** [comment]
https://github.com/mathwallet/Secp256k1Swift

Use this dependency package to create wallets

**Comment by yuzhiyou1990** [comment]
TronSigner.generate()

https://github.com/yuzhiyou1990/TronWebSwift/blob/master/Sources/TronWebSwift/Crypto/TronSigner.swift

**Comment by mnz12138** [comment]
I get the private key and address, can I get the mnemonic as well?

**Comment by yuzhiyou1990** [comment]
https://github.com/mathwallet/BIP39swift
Use this dependent package

**Comment by mnz12138** [comment]
Thank you. How are mnemonics involved in generating private keys and addresses

**Comment by yuzhiyou1990** [comment]
About using mnemonics to view this branch.
https://github.com/yuzhiyou1990/TronWebSwift/blob/bip39/Sources/TronWebSwift/Crypto/TronSigner.swift

**Comment by mnz12138** [comment]
Thank you very much! Your answer is very helpful to me

**Comment by mnz12138** [comment]
Using your library conflicts with secp256k1 in this library https://github.com/argentlabs/web3.swift
