### ISSUE TITLE
我不知道这个abi返回值解码要怎么用

### ISSUE THREAD

**Issue by ZackDT** [yuzhiyou1990/TronWebSwift#2]
你好，对这个decodeReturnData我不知道怎么使用。用刚编码出来的data，不行，去掉方法名的data，留下参数的data再去加码也不行。

        let toAddress = TronAddress("THcrPzcnm7KVxwKKoBsZN6fvC2xMb7ZMfD") 
        let powInput = pow(10, 6).doubleValue * 0.1
        let inputBig = BigInt(Int(powInput))
        let parameters = [toAddress, inputBig] as [AnyObject]
        // uint256
        
        // 1、获取参数abi签名
        let tronContract = TronContract(TronWeb.Utils.trc20ABI, at: nil)
        guard var data = tronContract?.encode(method: "transfer", parameters: parameters) else {
            ez.toast("签名失败，请重新尝试")
            return
        }
        guard data.count > 4 else {
            ez.toast("签名失败，请重新尝试")
            return
        }
        QL2("\(data.count)=======\(data.hexString)")
        let dataSuf4: Data = data.suffix(from: 4)
        QL2("\(dataSuf4.count)=======\(dataSuf4.hexString)")
        let dict = tronContract?.decodeReturnData("transfer", data: dataSuf4)
        QL2("dict: \(dict)")

**Comment by yuzhiyou1990** [comment]
{
	"constant": false,
	"inputs": [{
		"name": "_to",
		"type": "address"
	}, {
		"name": "_value",
		"type": "uint256"
	}],
	"name": "transfer",
	"outputs": [{
		"name": "success",
		"type": "bool"
	}],
	"payable": false,
	"type": "function"
}

decodeReturnData 是在调用合约方法成功后，解析方法返回参数使用。

transfer方法的outputs 是 "success" 类型是 bool, 代码如下：
let returns = tronContract?.decodeReturnData("transfer", data: Data(hex: "0000000000000000000000000000000000000000000000000000000000000001"))
returns -> ["success": 1, "0": 1]

**Comment by yuzhiyou1990** [comment]
https://github.com/yuzhiyou1990/TronWebSwift/blob/master/Sources/TronWebSwift/TronWeb/TronWeb%2BContract.swift

看一下read 或 write方法

**Comment by ZackDT** [comment]
谢谢回复。我用了你TronWebSwift库的签名方法和ABI的编码,，但是和Dapp对接过程中需要显示要签名的Data(hex""a9059cbb00000000000000000000004141a768c9797b8b1a1d41d25ba603f68326fcfc4000000000000000000000000000000000000000000000000000000000000186a0"")的结果，例如address，uint256。
类似于
![image](https://user-images.githubusercontent.com/15107710/195524034-87159946-25cd-4b0e-a680-cda4b69c9bcb.png)

**Comment by yuzhiyou1990** [comment]
那你使用decodeInputData 方法，而不是 decodeReturnData

**Comment by yuzhiyou1990** [comment]
``` swift
func testDecodeInputDataExample() throws {
        guard let tronContract = TronContract(TronWeb.Utils.trc20ABI, at: nil) else { return }
        let method = "transfer"
        guard let function = tronContract.methods[method] else { return }
        guard case .function(_) = function else { return}
        // a9059cbb
        // 00000000000000000000004141a768c9797b8b1a1d41d25ba603f68326fcfc40
        // 00000000000000000000000000000000000000000000000000000000000186a0
        let returns = function.decodeInputData(Data(hex: "a9059cbb00000000000000000000004141a768c9797b8b1a1d41d25ba603f68326fcfc4000000000000000000000000000000000000000000000000000000000000186a0"))
        debugPrint(returns ?? [:])
}

```
使用最新代码，尝试使用这个方法

**Comment by ZackDT** [comment]
我增加了一个方法，方法如下：
![image](https://user-images.githubusercontent.com/15107710/195531001-2872215d-7927-415e-ac78-e035b4989dc8.png)

调用代码同上，结果出现地址没有解析出来，addressw为nil
![image](https://user-images.githubusercontent.com/15107710/195531159-7ede199b-6c78-4026-bef8-089b488d915e.png)

**Comment by yuzhiyou1990** [comment]
已修复这个问题，你看一下最新提交的代码，漏掉了地址前一个字节版本号导致
```
// let dataSlice = elementItself[12 ..< 32] 改
let dataSlice = elementItself[11 ..< 32]
```

**Comment by ZackDT** [comment]
非常感谢，完美的解决了这个问题。

**Comment by yuzhiyou1990** [comment]
TronContract 新增了 decodeMethodData ，根据data自动解析出方法名称和参数，代码如下
```Swift
guard let tronContract = TronContract(TronWeb.Utils.trc20ABI, at: nil) else { return }
let returns = tronContract.decodeMethodData(Data(hex: "a9059cbb00000000000000000000004141a768c9797b8b1a1d41d25ba603f68326fcfc4000000000000000000000000000000000000000000000000000000000000186a0"))
XCTAssertTrue(returns?.method == "transfer(address,uint256)")
XCTAssertTrue(returns?.inputs?["_value"] as? BigUInt == BigUInt("100000"))
```

**Comment by ZackDT** [comment]
尝试了下代码，发现对地址是hex格式的支持不了


guard let tronContract = TronContract(TronWeb.Utils.trc20ABI, at: nil) else { return }
        // transfer  地址是Base58格式
        let data2 = "a9059cbb00000000000000000000004141a768c9797b8b1a1d41d25ba603f68326fcfc4000000000000000000000000000000000000000000000000000000000000186a0"
        
        // approve  地址是hex格式
        let data1 = "095ea7b300000000000000000000000094f24e992ca04b49c6f2a2753076ef8938ed4daa0000000000000000000000000000000000000000000000000000000000000001"
        guard let inputDict = tronContract.decodeInputData(method: "transfer", Data(hex: data2))else {
            QL4("tronContract.decodeMethodData(Data(hex: contractParameterValueModel.data))")
            return
        }

我对你TronAddress类初始化方法init?(_ string: String)做了下改动，支持hex格式。如果解码需要支持hex地址的话，我需要怎么改动下面吗？
![image](https://user-images.githubusercontent.com/15107710/195563734-38eaae88-925c-47f1-a6df-1600411e72d4.png)

**Comment by yuzhiyou1990** [comment]
![image](https://user-images.githubusercontent.com/3783037/195567768-b900cffc-70bd-48be-9f72-0d585fd78199.png)
图上地址解析代码, 强制使用固定的地址版本即可
``` swift
// let dataSlice = elementItself[11 ..< 32] 改成
 let dataSlice = Data([TronAddress.addressPrefix]) + elementItself[12 ..< 32]
```
