### ISSUE TITLE
消息签名不对，少加了个27

### ISSUE THREAD

**Issue by ZackDT** [yuzhiyou1990/TronWebSwift#4]
![20221125174649](https://user-images.githubusercontent.com/15107710/203951623-68e126d5-e276-4c11-b9fe-b208e9aae449.jpg)

guard var signData = signDigest(hash) else {
            return nil
        }
signData[64] += 27
return signData

同ETH的消息签名一样。eth消息签名也会加个27。你这里少加了个。不加验证失败

**Comment by yuzhiyou1990** [comment]
不加27，也可以被验证。
如果你有额外的需求，可以自己fork进行修改。
![image](https://user-images.githubusercontent.com/3783037/205563373-72b9a9fd-baeb-4d03-b8f2-0cb07ae06ed3.png)

**Comment by ZackDT** [comment]
![image](https://user-images.githubusercontent.com/15107710/205580535-7fa0dd72-26ac-48ae-95a6-f0442b12b229.png)
刚试了下，不加也是可以验证成功。
打扰了。因为我看到TRX前面出来的也是加了27的结果。
浏览器上面的签名后面和加了27之后的是一样的
