### ISSUE TITLE
麻烦update一下Secp256k1Swift至1.3.1，谢谢

### ISSUE THREAD

**Issue by powfulhong** [yuzhiyou1990/TronWebSwift#5]
https://github.com/mathwallet/Secp256k1Swift.git", from: "1.3.1"

**Comment by yuzhiyou1990** [comment]
https://github.com/mathwallet/TronWebSwift/blob/master/Package.swift

目前已指向 Secp256k1Swift 1.3.1

**Comment by powfulhong** [comment]
但好像我用spm导入tronwebswift，导入不进来。。然后secp改为1.0.4，就能导入

**Comment by powfulhong** [comment]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/2617250/205874960-7bde2af7-5e64-436e-8b1e-22a12dc024fc.png">

**Comment by powfulhong** [comment]
<img width="573" alt="image" src="https://user-images.githubusercontent.com/2617250/205884665-7ee8ce07-1590-4fa4-926e-f29b1f490a55.png">
base58和ripemdswift链接不存在

**Comment by yuzhiyou1990** [comment]
Base58Swift和RIPEMDSwift链接不存在问题已修复

https://github.com/mathwallet/Base58Swift
https://github.com/mathwallet/RIPEMDSwift

**Comment by powfulhong** [comment]
非常感谢，我前几天通过spm导入其他仓库的base58swift，这样能成功导入TronWebSwift，但版本不是最新的。谢谢~
