### ISSUE TITLE
TronTriggerSmartContractExtension没有 public init

### ISSUE THREAD

**Issue by WSMI052** [yuzhiyou1990/TronWebSwift#9]
请问是否可以将该结构模型添加  public init ？

provider 里头的 triggerConstantContract 方法需要使用到
但无法建立该结构....

谢谢你

**Comment by yuzhiyou1990** [comment]
你 fork 一个分支，根据你的需求修改即可。

**Comment by WSMI052** [comment]
@yuzhiyou1990 谢谢您的答复
但我不理解为什么基础的 Struct 没有 Implicit Initializer

**Comment by yuzhiyou1990** [comment]
https://github.com/mathwallet/TronWebSwift/blob/master/Sources/TronWebSwift/Contracts/TronContract.swift#L74
实例化可参考TronContract 中的method 方法，通过 ABI 相关方法和参数进行构建，更容易、方便。
